/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type Address struct {

	Address string `json:"address"`

	Address2 string `json:"address2,omitempty"`

	City string `json:"city,omitempty"`

	State string `json:"state,omitempty"`

	ZipCode string `json:"zip_code"`

	Country string `json:"country"`

	Coordinates Coordinates `json:"coordinates,omitempty"`
}
