/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

import (
	"time"
)

type Batch struct {

	Id string `json:"id,omitempty"`

	State string `json:"state,omitempty"`

	ErrorMessages []string `json:"error_messages,omitempty"`

	Quantity int32 `json:"quantity,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	Href string `json:"href,omitempty"`

	Project Href `json:"project,omitempty"`

	Instances Href `json:"instances,omitempty"`
}
