/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type BgpConfigRequestInput struct {

	DeploymentType string `json:"deployment_type"`

	Asn int32 `json:"asn"`

	Md5 string `json:"md5,omitempty"`

	UseCase string `json:"use_case,omitempty"`
}
