/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type BgpSession struct {

	Id string `json:"id,omitempty"`

	Status string `json:"status,omitempty"`

	LearnedRoutes []string `json:"learned_routes,omitempty"`

	AddressFamily string `json:"address_family,omitempty"`

	Device Href `json:"device,omitempty"`

	Href string `json:"href,omitempty"`
}
