/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type CapacityPerBaremetal struct {

	Level string `json:"level,omitempty"`

	AvailableServers int32 `json:"available_servers,omitempty"`

	TotalServers int32 `json:"total_servers,omitempty"`

	MarketBufferPercentage int32 `json:"market_buffer_percentage,omitempty"`

	MarketFloorPrice float32 `json:"market_floor_price,omitempty"`
}
