/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type CapacityPerFacility struct {

	Baremetal0 CapacityPerBaremetal `json:"baremetal_0,omitempty"`

	Baremetal1 CapacityPerBaremetal `json:"baremetal_1,omitempty"`

	Baremetal2 CapacityPerBaremetal `json:"baremetal_2,omitempty"`

	Baremetal3 CapacityPerBaremetal `json:"baremetal_3,omitempty"`
}
