/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type CapacityReport struct {

	Ams1 CapacityPerFacility `json:"ams1,omitempty"`

	Ewr1 CapacityPerFacility `json:"ewr1,omitempty"`

	Sjc1 CapacityPerFacility `json:"sjc1,omitempty"`
}
