/*
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

import (
	"time"
)

type Device struct {
	Id string `json:"id,omitempty"`

	ShortId string `json:"short_id,omitempty"`

	Hostname string `json:"hostname,omitempty"`

	Description string `json:"description,omitempty"`

	State string `json:"state,omitempty"`

	Tags []string `json:"tags,omitempty"`

	ImageUrl string `json:"image_url,omitempty"`

	BillingCycle string `json:"billing_cycle,omitempty"`

	User string `json:"user,omitempty"`

	Iqn string `json:"iqn,omitempty"`

	Locked bool `json:"locked,omitempty"`

	BondingMode int32 `json:"bonding_mode,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	SpotInstance bool `json:"spot_instance,omitempty"`

	SpotPriceMax float32 `json:"spot_price_max,omitempty"`

	TerminationTime time.Time `json:"termination_time,omitempty"`

	ProvisioningPercentage float32 `json:"provisioning_percentage,omitempty"`

	OperatingSystem OperatingSystem `json:"operating_system,omitempty"`

	AlwaysPxe bool `json:"always_pxe,omitempty"`

	IpxeScriptUrl string `json:"ipxe_script_url,omitempty"`

	Location HardwareLocation `json:"location,omitempty"`

	Facility Facility `json:"facility,omitempty"`

	Plan Plan `json:"plan,omitempty"`

	Userdata string `json:"userdata,omitempty"`

	RootPassword string `json:"root_password,omitempty"`

	Href string `json:"href,omitempty"`

	// Full version of project object when included
	Project Href `json:"project,omitempty"`

	// Lite version of project object when included
	ProjectLite Href `json:"project_lite,omitempty"`

	Volumes []Href `json:"volumes,omitempty"`

	HardwareReservation Href `json:"hardware_reservation,omitempty"`

	SshKeys []Href `json:"ssh_keys,omitempty"`

	IpAddresses []IpAssignment `json:"ip_addresses,omitempty"`

	ProvisioningEvents []Event `json:"provisioning_events,omitempty"`
}
