/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type DeviceUpdateInput struct {

	Hostname string `json:"hostname,omitempty"`

	Description string `json:"description,omitempty"`

	BillingCycle string `json:"billing_cycle,omitempty"`

	Userdata string `json:"userdata,omitempty"`

	Locked bool `json:"locked,omitempty"`

	Tags []string `json:"tags,omitempty"`

	AlwaysPxe bool `json:"always_pxe,omitempty"`

	IpxeScriptUrl string `json:"ipxe_script_url,omitempty"`

	SpotInstance bool `json:"spot_instance,omitempty"`
}
