/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

import (
	"time"
)

type DeviceCreateInput struct {

	Facility string `json:"facility"`

	Plan string `json:"plan"`

	Hostname string `json:"hostname,omitempty"`

	Description string `json:"description,omitempty"`

	BillingCycle string `json:"billing_cycle,omitempty"`

	OperatingSystem string `json:"operating_system"`

	AlwaysPxe bool `json:"always_pxe,omitempty"`

	IpxeScriptUrl string `json:"ipxe_script_url,omitempty"`

	Userdata string `json:"userdata,omitempty"`

	Locked bool `json:"locked,omitempty"`

	HardwareReservationId string `json:"hardware_reservation_id,omitempty"`

	SpotInstance bool `json:"spot_instance,omitempty"`

	SpotPriceMax float32 `json:"spot_price_max,omitempty"`

	TerminationTime time.Time `json:"termination_time,omitempty"`

	Tags []string `json:"tags,omitempty"`

	ProjectSshKeys []string `json:"project_ssh_keys,omitempty"`

	UserSshKeys []string `json:"user_ssh_keys,omitempty"`

	Features []string `json:"features,omitempty"`
}
