/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

import (
	"time"
)

type Event struct {

	Id string `json:"id,omitempty"`

	State string `json:"state,omitempty"`

	Type_ string `json:"type,omitempty"`

	Body string `json:"body,omitempty"`

	Relationships []Href `json:"relationships,omitempty"`

	Interpolated string `json:"interpolated,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	Href string `json:"href,omitempty"`
}
