/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type HardwareLocation struct {

	Cage string `json:"cage,omitempty"`

	Facility string `json:"facility,omitempty"`

	Rack string `json:"rack,omitempty"`

	Row string `json:"row,omitempty"`

	Switch_ string `json:"switch,omitempty"`
}
