/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

import (
	"time"
)

type InternetGateway struct {

	Id string `json:"id,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	VirtualNetwork Href `json:"virtual_network,omitempty"`

	CreatedBy string `json:"created_by,omitempty"`

	IpReservations []Href `json:"ip_reservations,omitempty"`

	Href string `json:"href,omitempty"`
}
