/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

import (
	"time"
)

type Invitation struct {

	Id string `json:"id,omitempty"`

	Roles []string `json:"roles,omitempty"`

	Invitee string `json:"invitee,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	InvitedBy Href `json:"invited_by,omitempty"`

	Project Href `json:"project,omitempty"`

	Href string `json:"href,omitempty"`
}
