/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

import (
	"time"
)

type IpAssignment struct {

	Id string `json:"id,omitempty"`

	AddressFamily int32 `json:"address_family,omitempty"`

	Netmask string `json:"netmask,omitempty"`

	Public bool `json:"public,omitempty"`

	Enabled bool `json:"enabled,omitempty"`

	Cidr int32 `json:"cidr,omitempty"`

	Management bool `json:"management,omitempty"`

	Manageable bool `json:"manageable,omitempty"`

	AssignedTo Href `json:"assigned_to,omitempty"`

	Network string `json:"network,omitempty"`

	Address string `json:"address,omitempty"`

	Gateway string `json:"gateway,omitempty"`

	Href string `json:"href,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	ParentBlock ParentBlock `json:"parent_block,omitempty"`
}
