/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type License struct {

	Id string `json:"id,omitempty"`

	Description string `json:"description,omitempty"`

	LicenseKey string `json:"license_key,omitempty"`

	LicenseeProduct Href `json:"licensee_product,omitempty"`

	Size float32 `json:"size,omitempty"`

	Project Href `json:"project,omitempty"`
}
