/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type LicenseCreateInput struct {

	Description string `json:"description,omitempty"`

	Size float32 `json:"size,omitempty"`

	LicenseeProductId string `json:"licensee_product_id,omitempty"`
}
