/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type Meta struct {

	First Href `json:"first,omitempty"`

	Previous Href `json:"previous,omitempty"`

	Self Href `json:"self,omitempty"`

	Next Href `json:"next,omitempty"`

	Last Href `json:"last,omitempty"`

	Total int32 `json:"total,omitempty"`
}
