/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type Port struct {

	Id string `json:"id,omitempty"`

	Type_ string `json:"type,omitempty"`

	Name string `json:"name,omitempty"`

	Data interface{} `json:"data,omitempty"`

	Hardware Href `json:"hardware,omitempty"`

	ConnectedPort Href `json:"connected_port,omitempty"`

	Href string `json:"href,omitempty"`
}
