/*
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

import (
	"time"
)

type Project struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	MaxDevices interface{} `json:"max_devices,omitempty"`

	Members []Href `json:"members,omitempty"`

	Memberships []Href `json:"memberships,omitempty"`

	NetworkStatus interface{} `json:"network_status,omitempty"`

	Invitations []Href `json:"invitations,omitempty"`

	PaymentMethod Href `json:"payment_method,omitempty"`

	Devices []Href `json:"devices,omitempty"`

	SshKeys []Href `json:"ssh_keys,omitempty"`

	Volumes []Href `json:"volumes,omitempty"`

	BgpConfig Href `json:"bgp_config,omitempty"`
}
