/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type SnapshotPolicyInput struct {

	SnapshotCount int32 `json:"snapshot_count,omitempty"`

	SnapshotFrequency string `json:"snapshot_frequency,omitempty"`
}
