/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type UserUpdateInput struct {

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`

	PhoneNumber string `json:"phone_number,omitempty"`

	Timezone string `json:"timezone,omitempty"`

	Password string `json:"password,omitempty"`
}
