/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

import (
	"time"
)

type User struct {

	Id string `json:"id,omitempty"`

	ShortId string `json:"short_id,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`

	FullName string `json:"full_name,omitempty"`

	Email string `json:"email,omitempty"`

	TwoFactorAuth string `json:"two_factor_auth,omitempty"`

	AvatarUrl string `json:"avatar_url,omitempty"`

	MaxProjects int32 `json:"max_projects,omitempty"`

	CreditAmount float32 `json:"credit_amount,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	Timezone string `json:"timezone,omitempty"`

	FraudScore string `json:"fraud_score,omitempty"`

	LastLoginAt time.Time `json:"last_login_at,omitempty"`

	Emails []Href `json:"emails,omitempty"`

	Href string `json:"href,omitempty"`

	PhoneNumber string `json:"phone_number,omitempty"`
}
