/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type VirtualNetworkCreateInput struct {

	ProjectId string `json:"project_id,omitempty"`

	Description string `json:"description,omitempty"`

	Facility string `json:"facility,omitempty"`

	Vxlan int32 `json:"vxlan,omitempty"`

	Vlan int32 `json:"vlan,omitempty"`
}
