/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

type VirtualNetwork struct {

	Id string `json:"id,omitempty"`

	Description string `json:"description,omitempty"`

	Vxlan int32 `json:"vxlan,omitempty"`

	Facility Href `json:"facility,omitempty"`

	AssignedTo Href `json:"assigned_to,omitempty"`

	Href string `json:"href,omitempty"`
}
