/* 
 * Packet API
 *
 * This is the API for Packet. Interact with your devices, user account, and projects.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@packet.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package packswgo

import (
	"time"
)

type Volume struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Size int32 `json:"size,omitempty"`

	Locked bool `json:"locked,omitempty"`

	BillingCycle string `json:"billing_cycle,omitempty"`

	State string `json:"state,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	Project Href `json:"project,omitempty"`

	Facility Href `json:"facility,omitempty"`

	SnapshotPolicies []Href `json:"snapshot_policies,omitempty"`

	Attachments []Href `json:"attachments,omitempty"`

	Plan Plan `json:"plan,omitempty"`

	Href string `json:"href,omitempty"`
}
